### ISSUE TITLE
Some questions about the details of Bert impletation in this model.

### ISSUE THREAD

**Issue by fengliangjing** [cslydia/Hire-NER#1]
I'm not clear about the usage of bert in your model, since the version of bert and its format were not specified in your code. And after I get the bert embedding file, how can I use it in your code?

**Comment by cslydia** [comment]
You can initialize the bert embeddings in the function`read_instance`, and then call the `nn.Embedding` with `idx_seq_tensor` .

**Comment by fengliangjing** [comment]
谢谢回复！那么当我得到Embedding之后，如何加到模型里面呢？是与word_embs和char_features一起进行cat操作吗？

**Comment by cslydia** [comment]
是的，一起进行cat操作。
