### ISSUE TITLE
Question on Intnet

### ISSUE THREAD

**Issue by abh2k** [cslydia/Hire-NER#2]
Line 97 -> `char_cnn_out = self.char_cnn(char_embeds).transpose(2,1).contiguous()`
Here `self.char_cnn` has not been initialized. Or am i missing something?

**Comment by cslydia** [comment]
We only use the function `get_last_hiddens ` in IntNet.py, the function `get_all_hiddens ` is not called, so you can dismiss Lines#85-98.
